name: Run Gosec in CODESOURCERER

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Dependencies for Github Service
        run: |
          cd src/github
          go mod tidy

      - name: Install Dependencies for GenAI Service
        run: |
          cd src/genAi
          go mod tidy

      - name: Run Gosec for Github Service
        uses: securego/gosec@master
        with:
          args: ./src/github/...

      - name: Run Gosec for GenAI Service
        uses: securego/gosec@master
        with:
          args: ./src/genAi/...
